# Generated by Django 3.0.4 on 2020-10-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1002_auto_20191111_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_key', models.CharField(max_length=32)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestionServiceCategory')),
            ],
            options={
                'unique_together': {('recommendation_key', 'service_category')},
            },
        ),
    ]
