# Generated by Django 3.0.4 on 2020-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1003_recommendationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuserquestionsequence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='surveyuserquestionsequence',
            unique_together={('user', 'question', 'branch')},
        ),
    ]
